Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provision "shell", inline: <<-SCRIPT
      sudo apt-get update
      sudo apt-get install -y nginx python3-flask
    SCRIPT
  end
  config.vm.define "db" do |db|
    db.vm.box = "debian/bookworm64"
    db.vm.network "forwarded_port", guest: 80, host: 8081
    db.vm.provision "shell", inline: <<-SCRIPT
      sudo apt-get update
      sudo apt install -y mariadb-server
      sudo systemctl start mariadb
      sudo systemctl enable mariadb
  SCRIPT
  end
end
